f=input("Think a number if you done press enter")
a=input("+8 to your number if you done press enter")
b=input("+2 to your number if you done press enter")
c=input("-1 to your number if you done press enter")
d=input("+9 to your number if you done press enter")
e=input("- with you number what you take first")
print("I think it may be 18 am I right")
